name: Receive Token Update

on:
  repository_dispatch:
    types: [tokens-updated]

jobs:
  update-tokens:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout consumer repo with submodules
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fix submodule to latest main
        run: |
          cd figma-design-tokens
          git fetch origin main
          git checkout main
          git merge origin/main --allow-unrelated-histories

      - name: Install and Build Tokens
        run: |
          cd figma-design-tokens
          npm install
          node fixed-tokens.js
          node build.cjs

      - name: Copy CSS to public
        run: |
          mkdir -p public/styles
          cp figma-design-tokens/output/fixed-token.css public/styles/tokens.css

      - name: Commit & Push changes
        run: |
          git config user.name "TirthParikh7"
          git config user.email "tirth@contentenablers.com"
          git add public/styles/tokens.css
          git commit -m "♻️ Auto-update token CSS" || echo "No changes to commit"
          git push
