name: Receive Token Update

on:
  repository_dispatch:
    types: [tokens-updated]

jobs:
  update-tokens:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.GH_PAT }}  # Needed if the submodule repo is private

      - name: Debug path structure
        run: |
          echo "PWD: $(pwd)"
          ls -la
          ls -la figma-design-tokens || echo "❌ Submodule not found!"

      - name: Install & run token scripts
        run: |
          npm install
          node fixed-tokens.js
          node build.cjs

      - name: Copy CSS to public/styles
        run: |
          mkdir -p public/styles
          cp figma-design-tokens/output/fixed-token.css public/styles/tokens.css

      - name: Commit & push changes
        run: |
          git config user.name "TirthParikh7"
          git config user.email "tirth@contentenablers.com"
          git add public/styles/tokens.css
          git commit -m "♻️ Auto-update token CSS" || echo "No changes to commit"
          git push
