name: Receive Token Update

on:
  repository_dispatch:
    types: [tokens-updated]

jobs:
  update-tokens:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout consumer repo
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.GH_PAT }}  # Needed if the submodule repo is private

      - name: Pull latest tokens from submodule
        run: |
          git submodule update --init --force
          cd figma-design-tokens
          git fetch origin
          git checkout origin/main -- .
          cd ..

      - name: Debug path structure
        run: |
          echo "PWD: $(pwd)"
          ls -la
          echo "\nContents of figma-design-tokens:"
          ls -la figma-design-tokens || echo "❌ figma-design-tokens directory not found!"
          echo "\nContents of figma-design-tokens/output:"
          ls -la figma-design-tokens/output || echo "❌ figma-design-tokens/output directory not found!"

      - name: Copy pre-built CSS to public folder
        run: |
          mkdir -p public/styles
          cp figma-design-tokens/output/fixed-token.css public/styles/tokens.css # Assuming singular 'token'

      - name: Commit & push changes
        run: |
          git config user.name "TirthParikh7"
          git config user.email "tirth@contentenablers.com"
          git add public/styles/tokens.css
          git commit -m "♻️ Update token CSS from submodule" || echo "No changes to commit"
          git push