name: Receive Token Update

on:
  repository_dispatch:
    types: [tokens-updated]

jobs:
  update-tokens:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.GH_PAT }}  # Required if private repo

      - name: Verify submodule exists and is populated
        run: |
          echo "Checking submodule content..."
          ls -la
          ls -la figma-design-tokens
          ls -la figma-design-tokens/output || echo "No output dir yet"

      - name: Run token build scripts
        working-directory: ./figma-design-tokens
        run: |
          npm install
          node fixed-tokens.js
          node build.cjs

      - name: Copy CSS into consumer public/styles
        run: |
          mkdir -p public/styles
          cp figma-design-tokens/output/fixed-token.css public/styles/tokens.css

      - name: Commit and push updated CSS
        run: |
          git config user.name "TirthParikh7"
          git config user.email "tirth@contentenablers.com"
          git add public/styles/tokens.css
          git commit -m "♻️ Auto-update token CSS" || echo "No changes to commit"
          git push
