name: Receive Token Update

on:
  repository_dispatch:
    types: [tokens-updated]

jobs:
  update-tokens:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout consumer repo with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.GH_PAT }} # 👈 Required if your submodule repo is private

      - name: Confirm submodule content exists
        run: |
          ls -la figma-design-tokens

      - name: Install and build tokens
        run: |
          cd figma-design-tokens
          npm install
          node fixed-tokens.js
          node build.cjs

      - name: Copy generated CSS
        run: |
          mkdir -p public/styles
          cp figma-design-tokens/output/fixed-token.css public/styles/tokens.css

      - name: Commit & push updated CSS
        run: |
          git config user.name "TirthParikh7"
          git config user.email "tirth@contentenablers.com"
          git add public/styles/tokens.css
          git commit -m "♻️ Auto-update token CSS" || echo "No changes to commit"
          git push
